### ISSUE TITLE
Suggestions to Prevent Chat Spam

### ISSUE THREAD

**Issue by oitsjustjose** [LexManos/ChunkNoGoByeBye#2]
Just wanted to start by saying **thank you!** Your code made it easy for me to figure out a few concepts when porting Persistent Bits over to 1.14. In the process, I found a few tweaks/optimizations that I thought I'd suggest in case you were interested (these are no means critiques against your code; again: I would've been much more lost on my end without your code - mine would've probably been much more.. "nasty")

### Suggestion

Out of curiosity, why did you choose to implement Force Loaded chunks via the `/forceload` command? I'm sure it's something obvious that I'm just missing. If not, I noticed this:
 https://github.com/LexManos/ChunkNoGoByeBye/blob/ba0877e9a03615c8943cc9f9548903a85196857f/src/main/java/net/minecraftforge/lex/cngbb/ChunkLoaderList.java#L97

When I initially got Persistent Bits *working*, I too used this exact method thanks to your help. In an attempt to resolve this, I looked into the path that calling the `/forceload` command traverses down, and found `net.minecraft.world.server.ServerWorld$forceLoad` - which does the exact same thing but silently. See [here](https://github.com/oitsjustjose/Persistent-Bits/blob/a93f7da1d2572018db6d135f421b60f41ed1c114/src/main/java/com/oitsjustjose/persistentbits/common/capability/ChunkLoaderList.java#L90) - the last boolean arg represents whether to add said chunk; true = add, false = remove.

Overall, if you'd like me to make a PR to implement this (because I imagine you're definitely busy with much more important things), I'd be glad to - just let me know. Otherwise, it's honestly not *too* much chat spam considering it's only for the one chunk (as opposed to Persistent Bits which loads a radius of multiple chunks, thus getting *super* spammy).

**Comment by LexManos** [comment]
I used the command because that is the entire point of this mod, to use vanilla mechanics.
I also kinda like the spam, it lets users know if its done something {first one added/last one removed}
I put a lot of //TODO: ... ? comments in my code just as thoughts while i write it.

**Comment by oitsjustjose** [comment]
That makes sense. Maybe that's why so many people are coming to me about Persistent Bits asking why it isn't loading non-entities (e.g. wheat) -- maybe I'll look into implementing something to let users know!
