### ISSUE TITLE
[1.14.4] loaded chunks don't appear to be ticking

### ISSUE THREAD

**Issue by systemshaper** [LexManos/ChunkNoGoByeBye#4]
On our 1.14.4 server we noticed that crops weren't growing and sheep weren't regrowing wool in chunk loaded areas using this mod. Some things (like refined storage remote connections) were working correctly, so I think maybe the chunk is loaded but not ticking?

I also tested this in a single player world with all other mods removed. I set up a crop of wheat beside this chunk loader, then afk in a distant location. Each time I return, the crops have not grown at all.

Forge version 1.14.4 28.2.0
chunknogobyebye-1.14.4-1.0.3

**Comment by LexManos** [comment]
Notice how there are no xp orbs in the chunk i'm in, that is because there is a chunk loader in it and they timed out while the others were unloaded.
![](https://i.imgur.com/TTQfnsM.jpg)

Yes this was done in 1.15.2 but the code for chunkloading is the same.
