### ISSUE TITLE
Chunkloading Causing Dedicated Server Hang on Start

### ISSUE THREAD

**Issue by Chris3606** [LexManos/ChunkNoGoByeBye#7]
I am running a server using the Direwolf pack v1.7.  I recently laid down this mod's chunkloaders on several chunks around my base, and the first time after this that I restarted the server, it hangs on start; the startup process never completes and it does not crash.  Attached is the run log for reference, which shows a player being disconnected when they attempt to connect due to the server startup process being incomplete:
[2021-03-19-6.log](https://github.com/LexManos/ChunkNoGoByeBye/files/6174623/2021-03-19-6.log)

I left the sever alone for 10+ minutes and it never finished, and I tried restarting the server several times to no avail.  As soon as I removed the ChunkNoGoByeBye mod, the world loaded perfectly.

I know other mod's versions of chunkloading have had [similar issues](https://github.com/mekanism/Mekanism/issues/6174) in the past, in case it's helpful.

EDIT: To my knowledge, there's nothing corrupt going on in the chunks I'm loading, by the way; they seem to load fine with FTB chunks, FWIW.

**Comment by LexManos** [comment]
Unable to reproduce, and your log has coremods in it so I will provide zero support as they could be doing anything to screw things up.
So, try killing mods until it works.

**Comment by Chris3606** [comment]
Fair enough. I found another loader that works for the immediate need, but if I have spare time on a weekend I'll kill mods and if I get through all the core mods with something reproducible, will post something back, however truthfully it's unlikely. Thanks anyway.

**Comment by HeatherComputer** [comment]
Not sure if I should reopen this, but I was experiencing this issue (we've disabled chunkloaders this mod now) and I believe it was to do with when the chunk was forceloaded. What surprises me about this was that not even watchdog could kill the server.

I understand not much can be done without logs, which I no longer have to hand - however I do know the last line before the deadlock was the server responding to a forceload command. It happened about 50% of the time and when investigating the chunk, it indeed had one of these loaders and replacing it with a different one completly resolved the issue.
