### ISSUE TITLE
[Request] Force load detector

### ISSUE THREAD

**Issue by chimericdream** [LexManos/ChunkNoGoByeBye#8]
I routinely forget where I have placed chunk loaders, because I usually put them under a build, behind a wall, etc. I would love it if there were some kind of item that I could have which could tell me if the chunk I am standing in is force-loaded. It doesn't have to have a gui or be any kind of fancy. I'm imagining something like the clock, with the dial being one of the following:

Gray: chunk is not force-loaded
Pink (matching the color on the chunk loaders themselves): chunk is force-loaded by CNGBB
Green: chunk is force-loaded as part of the world spawn area

**Comment by LexManos** [comment]
Nope, too complex/out  of scope of this mod.  You can  view the list of forced chunks by looking at your  level.dat or using the /forceload query command
https://minecraft.fandom.com/wiki/Commands/forceload

**Comment by chimericdream** [comment]
That's fair. I wasn't sure what kind of effort it would be, but I appreciate the response.
